version: '2'
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cipherloans
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha
      - MAX_CONNECTIONS=300
    volumes:
      - ./tables.sql:/docker-entrypoint-initdb.d/setup.sql